apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway2
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: istio-mixer
    http:
      paths:
      - backend:
          serviceName: istio-mixer
          servicePort: 42422
  - host: istio-pilot
    http:
      paths:
      - backend:
          serviceName: istio-pilot
          servicePort: 15003
  - host: prometheus
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
